# Generated by Django 4.1.2 on 2022-10-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the full name of the item', max_length=50)),
                ('brand', models.CharField(help_text='Example: Torani', max_length=50)),
                ('unit', models.CharField(help_text='Example: Strawberry', max_length=50)),
                ('par', models.IntegerField(default=0)),
                ('current_qty', models.IntegerField(default=0)),
                ('upc_code', models.IntegerField(default=0, help_text='Store the unique 12-digit UPC code fetched from scanner')),
            ],
        ),
    ]
