# Generated by Django 4.1.2 on 2022-10-25 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Example: Torani', max_length=50)),
                ('unit', models.CharField(help_text='Example: Strawberry', max_length=50)),
                ('quota', models.IntegerField(default=0, help_text='The required minimum quantity when restocking has occurred')),
                ('storage', models.CharField(choices=[('A', 'Shed'), ('B', 'Shop')], max_length=2)),
                ('upc_code', models.IntegerField(default=0, help_text='Store the unique 12-digit UPC code fetched from scanner')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Dillanos', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_qty', models.IntegerField(default=0, help_text='The amount of a given item to be ordered')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier'),
        ),
    ]
