# Generated by Django 4.1.3 on 2022-11-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='package',
            field=models.CharField(blank=True, choices=[('BX', 'Box(es)'), ('C', 'Case(s)'), ('CRT', 'Carton(s)')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='package_qty',
            field=models.IntegerField(default=0, help_text='Quantity of unit per package'),
        ),
    ]
