# Generated by Django 4.1.2 on 2022-10-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_qty',
            field=models.IntegerField(default=0, help_text='The actual amount available prior to ordering'),
        ),
        migrations.AlterField(
            model_name='item',
            name='par',
            field=models.IntegerField(default=0, help_text='The required minimum quantity when restocking has occurred'),
        ),
    ]
