# Generated by Django 4.1.3 on 2022-11-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_package_alter_item_package_qty'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='packaging',
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('package__length', 0), ('package_qty', 0)), models.Q(('package__length__gt', 0), ('package_qty__gt', 0)), _connector='OR'), name='packaging'),
        ),
    ]
