# Generated by Django 4.1.3 on 2022-11-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_email_supplier_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=0, help_text='The unique value used to identify an order'),
        ),
    ]
