# Generated by Django 4.1.3 on 2022-11-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_item_packaging_item_packaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='package',
            field=models.CharField(blank=True, choices=[('box(es)', 'Box(es)'), ('case(s)', 'Case(s)'), ('carton(s)', 'Carton(s)')], default='', max_length=10),
        ),
    ]
