# Generated by Django 4.1.3 on 2022-11-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='upc_code',
        ),
        migrations.AddField(
            model_name='item',
            name='latest_qty',
            field=models.IntegerField(default=0, help_text='The last quantity ordered'),
        ),
    ]
