# Generated by Django 4.1.3 on 2022-12-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='send_email',
            field=models.BooleanField(default=True),
        ),
    ]
