# Generated by Django 4.1.3 on 2022-12-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_supplier_send_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='send_email',
            field=models.BooleanField(default=True, help_text='Set "True" if you want orders to be sent to supplier email'),
        ),
    ]
