# Generated by Django 4.1.3 on 2022-11-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_item_upc_code_item_latest_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='latest_qty',
            field=models.IntegerField(default=0, editable=False, help_text='The last quantity ordered'),
        ),
    ]
