# Generated by Django 4.1.3 on 2022-12-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_supplier_send_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, help_text='Example: Torani', max_length=50),
        ),
    ]
